set(BUILD_ASSETS_MPQ OFF)
set(USE_SDL1 ON)
set(NONET ON)
set(DEVILUTIONX_SYSTEM_LIBSODIUM OFF)
set(DEVILUTIONX_SYSTEM_BZIP2 OFF)

set(SDL1_VIDEO_MODE_BPP 32)
set(SDL1_VIDEO_MODE_FLAGS SDL_HWSURFACE)
set(SDL1_FORCE_SVID_VIDEO_MODE ON)

set(PREFILL_PLAYER_NAME ON)


# OpenDingux Beta does not currently support X-OD-NeedsJoystick,
# so we use KBCTRL instead. Unfortunately, this partially breaks
# external mouse and keyboard support.
set(HAS_KBCTRL 1)
set(KBCTRL_BUTTON_DPAD_LEFT SDLK_LEFT)
set(KBCTRL_BUTTON_DPAD_RIGHT SDLK_RIGHT)
set(KBCTRL_BUTTON_DPAD_UP SDLK_UP)
set(KBCTRL_BUTTON_DPAD_DOWN SDLK_DOWN)
set(KBCTRL_BUTTON_B SDLK_SPACE)
set(KBCTRL_BUTTON_A SDLK_LCTRL)
set(KBCTRL_BUTTON_Y SDLK_LSHIFT)
set(KBCTRL_BUTTON_X SDLK_LALT)
set(KBCTRL_BUTTON_RIGHTSHOULDER SDLK_t)
set(KBCTRL_BUTTON_LEFTSHOULDER SDLK_e)
set(KBCTRL_BUTTON_START SDLK_RETURN)
set(KBCTRL_BUTTON_BACK SDLK_RCTRL) # Select

