set(BUILD_ASSETS_MPQ OFF)
set(USE_SDL1 ON)
set(NONET ON)
set(DEVILUTIONX_SYSTEM_LIBSODIUM OFF)
set(DEVILUTIONX_SYSTEM_BZIP2 OFF)

set(SDL1_VIDEO_MODE_BPP 32)
set(SDL1_VIDEO_MODE_FLAGS SDL_HWSURFACE)
set(SDL1_FORCE_SVID_VIDEO_MODE ON)

set(PREFILL_PLAYER_NAME ON)
set(DEFAULT_AUDIO_SAMPLE_RATE 44100)

# The mini's buttons are connected via GPIO and are mapped to keyboard inputs
set(HAS_KBCTRL 1)
set(KBCTRL_BUTTON_DPAD_LEFT SDLK_LEFT)
set(KBCTRL_BUTTON_DPAD_RIGHT SDLK_RIGHT)
set(KBCTRL_BUTTON_DPAD_UP SDLK_UP)
set(KBCTRL_BUTTON_DPAD_DOWN SDLK_DOWN)
set(KBCTRL_BUTTON_B SDLK_SPACE) # Select spell
set(KBCTRL_BUTTON_A SDLK_LCTRL) # Attack
set(KBCTRL_BUTTON_Y SDLK_LSHIFT) # cast spell
set(KBCTRL_BUTTON_X SDLK_LALT) # pickup item
set(KBCTRL_BUTTON_RIGHTSHOULDER SDLK_t) # use mana potion
set(KBCTRL_BUTTON_LEFTSHOULDER SDLK_e) # use health potion
set(KBCTRL_BUTTON_START SDLK_TAB) # Use L2 for panel hotkeys
set(KBCTRL_BUTTON_BACK SDLK_BACKSPACE) # Use R2 for spell hotkeys

# Map start to menu and select to automap.
set(REMAP_KEYBOARD_KEYS "{SDLK_RETURN,SDLK_ESCAPE},{SDLK_RCTRL,SDLK_TAB}")
