set(ASAN OFF)
set(UBSAN OFF)
set(NONET ON)
set(DEVILUTIONX_SYSTEM_SDL_IMAGE OFF)
set(BUILD_TESTING OFF)
set(PREFILL_PLAYER_NAME ON)
set(NOEXIT ON)

# Use lower resampling quality for FPS.
set(DEFAULT_AUDIO_RESAMPLING_QUALITY 2)
