set(ASAN OFF)
set(UBSAN OFF)
set(BUILD_ASSETS_MPQ OFF)
set(BUILD_TESTING OFF)
set(DISCORD_INTEGRATION OFF)
set(DEVILUTIONX_GAMEPAD_TYPE Xbox)

# setting all libs to be built statically and from source
set(DEVILUTIONX_SYSTEM_SDL2 OFF)
set(DEVILUTIONX_SYSTEM_SDL_IMAGE OFF)
set(DEVILUTIONX_SYSTEM_SDL_AUDIOLIB OFF)
set(DEVILUTIONX_SYSTEM_LIBSODIUM OFF)
set(DEVILUTIONX_SYSTEM_LIBPNG OFF)
set(DEVILUTIONX_SYSTEM_LIBFMT OFF)
set(DEVILUTIONX_SYSTEM_BZIP2 OFF)
set(DEVILUTIONX_SYSTEM_ZLIB OFF)

set(DEVILUTIONX_STATIC_SDL2 ON)
set(DEVILUTIONX_STATIC_SDL_IMAGE ON)
set(DEVILUTIONX_STATIC_SDL_AUDIOLIB ON)
set(DEVILUTIONX_STATIC_LIBSODIUM ON)
set(DEVILUTIONX_STATIC_LIBPNG ON)
set(DEVILUTIONX_STATIC_LIBFMT ON)
set(DEVILUTIONX_STATIC_BZIP2 ON)
set(DEVILUTIONX_STATIC_ZLIB ON)

# not really necessary but a good measure for SDL related stuff
set(WINDOWS_STORE ON)

add_library(uwp_defs INTERFACE)
target_compile_definitions(uwp_defs INTERFACE __UWP__=1)
set(DEVILUTIONX_PLATFORM_ASSETS_LINK_LIBRARIES uwp_defs)
set(DEVILUTIONX_PLATFORM_LINK_LIBRARIES uwp_defs)
