set(ASAN OFF)
set(UBSAN OFF)
set(DEVILUTIONX_STATIC_CXX_STDLIB OFF)
set(BUILD_TESTING OFF)
set(DISABLE_ZERO_TIER ON)
set(PREFILL_PLAYER_NAME ON)

list(APPEND DEVILUTIONX_PLATFORM_LINK_LIBRARIES
  ScePower_stub
  SceAppUtil_stub
  SceNet_stub
  SceNetCtl_stub
)
list(APPEND DEVILUTIONX_PLATFORM_COMPILE_DEFINITIONS
  VITA
)
