set(ASAN OFF)
set(UBSAN OFF)
set(DIST ON)

list(APPEND DEVILUTIONX_PLATFORM_LINK_LIBRARIES
  find_steam_game
  shlwapi
  wsock32
  ws2_32
  wininet
)

if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
  list(APPEND DEVILUTIONX_PLATFORM_COMPILE_OPTIONS "/W3" "/Zc:__cplusplus" "/utf-8")
  list(APPEND DEVILUTIONX_PLATFORM_COMPILE_DEFINITIONS _CRT_SECURE_NO_WARNINGS)
else()
  list(APPEND DEVILUTIONX_PLATFORM_COMPILE_OPTIONS $<$<CONFIG:Debug>:-gstabs>)
endif()

if(MINGW_CROSS)
  list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/mingw")
endif()
