#pragma once

#define JOY_AXIS_LEFTX 0
#define JOY_AXIS_LEFTY 1
#define JOY_AXIS_RIGHTX 2
#define JOY_AXIS_RIGHTY 3
#define JOY_HAT_DPAD_UP_HAT 0
#define JOY_HAT_DPAD_UP 1
#define JOY_HAT_DPAD_DOWN_HAT 0
#define JOY_HAT_DPAD_DOWN 4
#define JOY_HAT_DPAD_LEFT_HAT 0
#define JOY_HAT_DPAD_LEFT 8
#define JOY_HAT_DPAD_RIGHT_HAT 0
#define JOY_HAT_DPAD_RIGHT 2
#define JOY_BUTTON_A 0
#define JOY_BUTTON_B 1
#define JOY_BUTTON_Y 2
#define JOY_BUTTON_X 3
#define JOY_BUTTON_LEFTSTICK 10
#define JOY_BUTTON_RIGHTSTICK 11
#define JOY_BUTTON_RIGHTSHOULDER 5
#define JOY_BUTTON_LEFTSHOULDER 4
#define JOY_BUTTON_TRIGGERLEFT 6
#define JOY_BUTTON_TRIGGERRIGHT 7
#define JOY_BUTTON_START 9
#define JOY_BUTTON_BACK 8