# See https://vcpkg.readthedocs.io/en/latest/users/manifests/
if(USE_SDL1)
  list(APPEND VCPKG_MANIFEST_FEATURES "sdl1")
else()
  list(APPEND VCPKG_MANIFEST_FEATURES "sdl2")
endif()
if(PACKET_ENCRYPTION)
  list(APPEND VCPKG_MANIFEST_FEATURES "encryption")
endif()
if(USE_GETTEXT_FROM_VCPKG)
  list(APPEND VCPKG_MANIFEST_FEATURES "translations")
endif()
if(BUILD_TESTING)
  list(APPEND VCPKG_MANIFEST_FEATURES "tests")
endif()
