/**
 * @file spelldat.h
 *
 * Interface of all spell data.
 */
#pragma once

#include <cstdint>

#include "effects.h"

namespace devilution {

#define MAX_SPELLS 52

enum spell_type : uint8_t {
	RSPLTYPE_SKILL,
	RSPLTYPE_SPELL,
	RSPLTYPE_SCROLL,
	RSPLTYPE_CHARGES,
	RSPLTYPE_INVALID,
};

enum spell_id : int8_t {
	SPL_NULL,
	SPL_FIREBOLT,
	SPL_HEALING,
	SPL_LIGHTNING,
	SPL_FLASH,
	SPL_IDENTIFY,
	SPL_FIREWALL,
	SPL_TOWNPORTAL,
	SPL_STONECURSE,
	SPL_INFRAVISION,
	SPL_PHASING,
	SPL_MANASHIELD,
	SPL_FIREBALL,
	SPL_GUARDIAN,
	SPL_CHAINLIGHTNING,
	SPL_FLAMEWAVE,
	SPL_DOOMSERP,
	SPL_BLODRIT,
	SPL_NOVA,
	SPL_INVISIBIL,
	SPL_INFERNO,
	SPL_GOLEM,
	SPL_RAGE,
	SPL_TELEPORT,
	SPL_APOCALYPSE,
	SPL_ETHEREALIZE,
	SPL_ITEMREPAIR,
	SPL_STAFFRECHARGE,
	SPL_DISARMTRAP,
	SPL_ELEMENTAL,
	SPL_CHARGEDBOLT,
	SPL_HOLYBOLT,
	SPL_RESURRECT,
	SPL_TELEKINESIS,
	SPL_HEALOTHER,
	SPL_BLOODSTAR,
	SPL_BONESPIRIT,
	SPL_LASTDIABLO = SPL_BONESPIRIT,
	SPL_MANA,
	SPL_MAGI,
	SPL_JESTER,
	SPL_LIGHTNINGWALL,
	SPL_IMMOLATION,
	SPL_WARP,
	SPL_REFLECT,
	SPL_BERSERK,
	SPL_RINGOFFIRE,
	SPL_SEARCH,
	SPL_RUNEFIRE,
	SPL_RUNELIGHT,
	SPL_RUNENOVA,
	SPL_RUNEIMMOLAT,
	SPL_RUNESTONE,

	SPL_LAST = SPL_RUNESTONE,
	SPL_INVALID = -1,
};

enum magic_type : uint8_t {
	STYPE_FIRE,
	STYPE_LIGHTNING,
	STYPE_MAGIC,
};

enum missile_id : int8_t {
	MIS_ARROW,
	MIS_FIREBOLT,
	MIS_GUARDIAN,
	MIS_PHASING,
	MIS_NOVA,
	MIS_FIREWALL,
	MIS_FIREBALL,
	MIS_LIGHTNINGC,
	MIS_LIGHTNING,
	MIS_MISSILEHIT,
	MIS_TOWNPORTAL,
	MIS_FLASH,
	MIS_FLASH2,
	MIS_MANASHIELD,
	MIS_FLAMEWAVE,
	MIS_CHAINLIGHTNING,
	MIS_NULL_10,
	MIS_NULL_11,
	MIS_NULL_12,
	MIS_NULL_13,
	MIS_RHINO,
	MIS_MAGMABALL,
	MIS_MLIGHTNINGC,
	MIS_MLIGHTNING,
	MIS_BLOODSTAR,
	MIS_MISSILEHIT2,
	MIS_TELEPORT,
	MIS_FIREARROW,
	MIS_NULL_1C,
	MIS_NULL_1D,
	MIS_STONECURSE,
	MIS_NULL_1F,
	MIS_NULL_20,
	MIS_GOLEM,
	MIS_NULL_22,
	MIS_NULL_23,
	MIS_APOCALYPSE,
	MIS_HEALING,
	MIS_FIREWALLC,
	MIS_INFRAVISION,
	MIS_IDENTIFY,
	MIS_FLAMEWAVEC,
	MIS_IMMOLATION1,
	MIS_RAGE,
	MIS_APOCALYPSEC,
	MIS_ITEMREPAIR,
	MIS_STAFFRECHARGE,
	MIS_DISARMTRAP,
	MIS_INFERNO,
	MIS_INFERNOC,
	MIS_NULL_32,
	MIS_NULL_33,
	MIS_CHARGEDBOLT,
	MIS_HOLYBOLT,
	MIS_RESURRECT,
	MIS_TELEKINESIS,
	MIS_LIGHTNINGARROW,
	MIS_ACID,
	MIS_MISSILEHIT3,
	MIS_ACIDPUDDLE,
	MIS_HEALOTHER,
	MIS_ELEMENTAL,
	MIS_RESURRECTBEAM,
	MIS_BONESPIRIT,
	MIS_ELEMENTMELEEHIT,
	MIS_REDPORTAL,
	MIS_DAPOCALYPSE,
	MIS_DAPOCALYPSEC,
	MIS_MANA,
	MIS_MAGI,
	MIS_LIGHTNINGWALL,
	MIS_LIGHTNINGWALLC,
	MIS_IMMOLATIONC,
	MIS_SPECARROW,
	MIS_IMMOLATION,
	MIS_BOWLIGHTNING,
	MIS_BOWCHARGEDBOLT,
	MIS_BOWHOLYBOLT,
	MIS_WARP,
	MIS_REFLECT,
	MIS_BERSERK,
	MIS_RINGOFFIRE,
	MIS_STEALPOTS,
	MIS_MANATRAP,
	MIS_NULL_54,
	MIS_SEARCH,
	MIS_NULL_56,
	MIS_NULL_57,
	MIS_NULL_58,
	MIS_RUNEFIRE,
	MIS_RUNELIGHT,
	MIS_RUNENOVA,
	MIS_RUNEIMMOLAT,
	MIS_RUNESTONE,
	MIS_HIVEEXP,
	MIS_HORKDMN,
	MIS_JESTER,
	MIS_HIVEEXP2,
	MIS_LICH,
	MIS_PSYCHORB,
	MIS_NECROMORB,
	MIS_ARCHLICH,
	MIS_BONEDEMON,
	MIS_EXYEL2,
	MIS_EXRED3,
	MIS_EXBL2,
	MIS_EXBL3,
	MIS_EXORA1,
	MIS_NULL = -1,
};

struct SpellData {
	spell_id sName;
	uint8_t sManaCost;
	magic_type sType;
	const char *sNameText;
	const char *sSkillText;
	int sBookLvl;
	int sStaffLvl;
	bool sTargeted;
	bool sTownSpell;
	int sMinInt;
	_sfx_id sSFX;
	missile_id sMissiles[3];
	uint8_t sManaAdj;
	uint8_t sMinMana;
	int sStaffMin;
	int sStaffMax;
	int sBookCost;
	int sStaffCost;
};

extern const SpellData spelldata[];

} // namespace devilution
